/* Marek Ledvina © Foriero s.r.o. 2022, The Commercial License */
using System.Collections;
using System.Collections.Generic;

namespace ForieroEngine.Music.Training
{
    public static partial class TL
    {
        public static partial class Enums
        {
            public static class MIDI
            {
                // general MIDI  list
                public enum ProgramEnum
                {
                    AcousticGrandPiano = 0,
                    BrightAcoustic = 1,
                    ElectricGrand = 2,
                    HonkyTonk = 3,
                    ElectricPiano = 4,
                    ElectricPianoB = 5,
                    Harpsichord = 6,
                    Clav = 7,
                    Celesta = 8,
                    Glockenspiel = 9,
                    MusicBox = 10,
                    Vibraphone = 11,
                    Marimba = 12,
                    Xylophone = 13,
                    TubularBells = 14,
                    Dulcimer = 15,
                    DrawbarOrgan = 16,
                    PercussiveOrgan = 17,
                    RockOrgan = 18,
                    ChurchOrgan = 19,
                    ReedOrgan = 20,
                    Accordian = 21,
                    Harmonica = 22,
                    TangoAccordian = 23,
                    AcousticGuitarNylon = 24,
                    AcousticGuitarSteel = 25,
                    ElectricGuitarJazz = 26,
                    ElectricGuitarClean = 27,
                    ElectricGuitarMuted = 28,
                    OverdrivenGuitar = 29,
                    DistortionGuitar = 30,
                    GuitarHarmonics = 31,
                    AcousticBass = 32,
                    ElectricBassFinger = 33,
                    ElectricBassPick = 34,
                    FretlessBass = 35,
                    SlapBass = 36,
                    SlapBassB = 37,
                    SynthBass = 38,
                    SynthBassB = 39,
                    Violin = 40,
                    Viola = 41,
                    Cello = 42,
                    Contrabass = 43,
                    TremoloStrings = 44,
                    PizzicatoStrings = 45,
                    OrchestralHarp = 46,
                    Timpani = 47,
                    StringEnsemble = 48,
                    StringEnsembleB = 49,
                    SynthStrings = 50,
                    SynthStringsB = 51,
                    ChoirAahs = 52,
                    ChoirOohs = 53,
                    SynthVoice = 54,
                    OrchestraHit = 55,
                    Trumpet = 56,
                    Trombone = 57,
                    Tuba = 58,
                    MutedTrumpet = 59,
                    FrenchHorn = 60,
                    BrassSection = 61,
                    SynthBrass = 62,
                    SynthBrassB = 63,
                    SopranoSax = 64,
                    AltoSax = 65,
                    TenorSax = 66,
                    BaritoneSax = 67,
                    Oboe = 68,
                    EnglishHorn = 69,
                    Bassoon = 70,
                    Clarinet = 71,
                    Piccolo = 72,
                    Flute = 73,
                    Recorder = 74,
                    PanFlute = 75,
                    BlownBottle = 76,
                    Shakuhachi = 77,
                    Whistle = 78,
                    Ocarina = 79,
                    LeadSquare = 80,
                    LeadSawtooth = 81,
                    LeadCalliope = 82,
                    LeadChiff = 83,
                    LeadCharang = 84,
                    LeadVoice = 85,
                    LeadFifths = 86,
                    LeadBassLead = 87,
                    PadNewAge = 88,
                    PadWarm = 89,
                    PadPolysynth = 90,
                    PadChoir = 91,
                    PadBowed = 92,
                    PadMetallic = 93,
                    PadHalo = 94,
                    PadSweep = 95,
                    FXRain = 96,
                    FXSoundtrack = 97,
                    FXCrystal = 98,
                    FXAtmosphere = 99,
                    FXBrightness = 100,
                    FXGoblins = 101,
                    FXEchoes = 102,
                    FXSciFi = 103,
                    Sitar = 104,
                    Banjo = 105,
                    Shamisen = 106,
                    Koto = 107,
                    Kalimba = 108,
                    Bagpipe = 109,
                    Fiddle = 110,
                    Shanai = 111,
                    TinkleBell = 112,
                    Agogo = 113,
                    SteelDrums = 114,
                    Woodblock = 115,
                    TaikoDrum = 116,
                    MelodicTom = 117,
                    SynthDrum = 118,
                    ReverseCymbal = 119,
                    GuitarFretNoise = 120,
                    BreathNoise = 121,
                    Seashore = 122,
                    BirdTweet = 123,
                    TelephoneRing = 124,
                    Helicopter = 125,
                    Applause = 126,
                    Gunshot = 127
                }

                public enum PercussionEnum
                {
                    AcousticBassDrum = 35,
                    BassDrum1 = 36,
                    SideStick = 37,
                    AcousticSnare = 38,
                    HandClap = 39,
                    ElectricSnare = 40,
                    LowFloorTom = 41,
                    ClosedHi_Hat = 42,
                    HighFloorTom = 43,
                    PedalHi_Hat = 44,
                    LowTom = 45,
                    OpenHi_Hat = 46,
                    Low_MidTom = 47,
                    Hi_MidTom = 48,
                    Crash_Cymbal1 = 49,
                    HighTom = 50,
                    RideCymbal1 = 51,
                    ChineseCymbal = 52,
                    RideBell = 53,
                    Tambourine = 54,
                    SplashCymbal = 55,
                    Cowbell = 56,
                    CrashCymbal2 = 57,
                    Vibraslap = 58,
                    RideCymbal2 = 59,
                    HiBongo = 60,
                    LowBongo = 61,
                    MuteHiConga = 62,
                    OpenHiConga = 63,
                    LowConga = 64,
                    HighTimbale = 65,
                    LowTimbale = 66,
                    HighAgogo = 67,
                    LowAgogo = 68,
                    Cabasa = 69,
                    Maracas = 70,
                    ShortWhistle = 71,
                    LongWhistle = 72,
                    ShortGuiro = 73,
                    LongGuiro = 74,
                    Claves = 75,
                    HighWoodBlock = 76,
                    LowWoodBlock = 77,
                    MuteCuica = 78,
                    OpenCuica = 79,
                    MuteTriangle = 80,
                    OpenTriangle = 81
                }
            }
        }
    }
}
